### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by askquickly** [liverecord/liverecord#5]
1. Environment is Debian 9
2. Docker compose up

After trying to build the docker I get:

`Error: could not get uid/gid
[ 'nobody', 0 ]

    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:76:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:224:22)
    at /usr/lib/node_modules/npm/lib/npm.js:262:24
    at /usr/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:171:20)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:229:22)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:378:26)
ERROR: Service 'web' failed to build: The command '/bin/sh -c apk --no-cache add --virtual native-deps   g++ gcc libgcc libstdc++ linux-headers   vips-dev fftw-dev autoconf automake nasm gifsicle libjpeg-turbo-utils optipng   openssl-dev make python   --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ &&   npm install --quiet node-gyp -g &&  npm install --quiet &&   apk del native-deps' returned a non-zero code: 7
`

**Comment by zoonman** [comment]
Sorry, I haven't updated dependencies for a while. 

```
WARNING: This apk-tools is OLD! Some packages might not function properly.

...
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! write after end
```
I will take a look when I will get a chance. I don't have large plans to support this package because I am working on a newer version based on `go` and modern version of angular.

**Comment by zoonman** [comment]
You can install nvm and MongoDB and run it without Docker.
It will complain but it will work. Follow the documentation here https://github.com/liverecord/liverecord/tree/master/docs
